### ISSUE TITLE
Autosplitter not working with RetroArch

### ISSUE THREAD

**Issue by icekitsune** [SonicSpeedrunning/LiveSplitASL#1]
OS: Windows 7 Home Premium SP1 - 64-bit
LiveSplit: 1.7.6
RetroArch: 1.7.3 (32-bit and 64-bit) - Genesis Plus GX 1.7.4

I've tried using the autosplitter with Fusion, and it works as expected. 

With RetroArch, the timer doesn't start when I begin a new game. If I manually start the timer, then a new game, the timer resets itself. This happens with both the 32-bit and 64-bit builds of RetroArch.

Running LiveSplit in Administrator Mode gives me the same result.

**Comment by beninswe** [comment]
This should now be fixed with commit #11  :)
